---
# Unquoted variables used with mode in the template module will for some reason
# translate to incorrect permissions. Example: 0644 becomes 420

yubikey_packages:
 - gnupg
 - openssh
 - opensc
 - ccid
 - libusb-compat
 - libu2f-host

yubikey_files:
 - file: .pam_environment
   mode: '0644'
 - file: .gnupg/gpg-agent.conf
   mode: '0600'
 - file: .gnupg/scdaemon.conf
   mode: '0600'
 - file: .config/autostart/gnome-keyring-ssh.desktop
   mode: '0644'

yubikey_dirs:
 - dir: .gnupg
   mode: '0700'
 - dir: .config/autostart
   mode: '0755'

yubikey_rescue:
  - path: /etc/systemd/system/socket.target.wants
    state: directory
  - path: /etc/systemd/system/socket.target.wants/pcscd.socket
    src: /usr/lib/systemd/system/pcscd.socket
    state: link
