---
- src: https://github.com/AsavarTzeth/ansible-role-aur
  version: master
  name: aur
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-gnome
  version: master
  name: gnome
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-grub
  version: master
  name: grub
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-hosts
  version: master
  name: hosts
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-sys-config
  version: master
  name: sys-config
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-users
  version: master
  name: users
  scm: git

