---
- src: https://github.com/AsavarTzeth/ansible-role-aur
  version: master
  name: AsavarTzeth.aur
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-gnome
  version: master
  name: AsavarTzeth.gnome
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-grub
  version: master
  name: AsavarTzeth.grub
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-hosts
  version: master
  name: AsavarTzeth.hosts
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-sys-config
  version: master
  name: AsavarTzeth.sys-config
  scm: git
- src: https://github.com/AsavarTzeth/ansible-role-users
  version: master
  name: AsavarTzeth.users
  scm: git

