- hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: check if in chroot
      shell: '[ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]
             && echo true || echo false'
      register: chroot
      changed_when: false
      tags: always

    - name: set chroot_mode
      set_fact: chroot_mode={{ true if chroot.stdout == 'true' else false }}
      tags: always

    - name: verify boot mode
      stat: path=/sys/firmware/efi/efivars
      register: efi
      when: boot_manager is undefined
      tags: grub,systemd-boot

    - name: set boot_manager
      set_fact: boot_manager={{ 'systemd-boot' if efi.stat.exists else 'grub' }}
      when: boot_manager is undefined
      tags: grub,systemd-boot

  roles:
    - time-zone
    - locale
    - network
    - root
    - reflector
    - { role: systemd-boot, when: boot_manager == 'systemd-boot' }
    - { role: grub, when: boot_manager == 'grub' }
    - users
    - sudo
    - systemd-timesyncd
    - packages
    - networkmanager
    - pulseaudio
    - xorg
    - nvidia
    - vulkan
    - gnome
    - yubikey
    - openvpn
    - gsettings
    - hidpi
