- hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  roles:
    - time-zone
    - locale
    - network
    - root
    - systemd-boot
    - reflector
    - users
    - sudo
    - systemd-timesyncd
    - packages
    - networkmanager
    - pulseaudio
