---
- block:
  - name: set amd packages
    set_fact:
      driver_pkg: "{{ driver_pkg }} + {{ amd_pkg }} + {{ amd_pkg_lib32 }}"
      vlk_pkg: "{{ vlk_pkg }} + {{ amd_vlk_pkg }} + {{ amd_vlk_pkg_lib32 }}"
    when: ansible_architecture == "x86_64"

  - name: set amd packages (x86)
    set_fact:
      driver_pkg: "{{ driver_pkg }} + {{ amd_pkg }}"
      vlk_pkg: "{{ vlk_pkg }} + {{ amd_vlk_pkg }}"
    when: ansible_architecture == "x86"

  tags: amd
  become: false
