---
- block:
  - set_fact:
      amd_packages: "{{ amd_packages }} {{ amd_packages_lib32 }}"
      vulkan_packages: "{{ vulkan_packages }} + {{ amd_vulkan_packages }}"
    when: ansible_architecture == "x86_64"
    become: false

  # Until mesa fully supports libglvnd do not install mesa drivers
  # when nvidia graphics is in use.
  - name: install amd/ati drivers
    pacman:
      name: "{{ amd_packages }}"
      update_cache: true
    when: graphics.stdout.find('NVIDIA') == -1

  tags: amd
  become: true
