---
- block:
  - set_fact:
      intel_packages: "{{ intel_packages }} {{ intel_packages_lib32 }}"
      vulkan_packages: "{{ vulkan_packages }} + {{ intel_vulkan_packages }}"
    when: ansible_architecture == "x86_64"
    become: false

  # Until mesa fully supports libglvnd do not install mesa drivers
  # when nvidia graphics is in use.
  - name: install intel drivers
    pacman:
      name: "{{ intel_packages }}"
      update_cache: true
    when: graphics.stdout.find('NVIDIA') == -1

  tags: intel
  become: true
