---
- block:
  - name: set intel packages
    set_fact:
      driver_pkg: "{{ driver_pkg }} + {{ intel_pkg }} + {{ intel_pkg_lib32 }}"
      vlk_pkg: "{{ vlk_pkg }} + {{ intel_vlk_pkg }} + {{ intel_vlk_pkg_lib32 }}"
    when: ansible_architecture == "x86_64"

  - name: set intel packages (x86)
    set_fact:
      driver_pkg: "{{ driver_pkg }} + {{ intel_pkg }}"
      vlk_pkg: "{{ vlk_pkg }} + {{ intel_vlk_pkg }}"
    when: ansible_architecture == "x86"

  tags: intel
  become: false
