---
- name: find graphics hardware
  shell: lspci | grep -e VGA -e 3D
  register: graphics
  changed_when: false
  become: false
  tags: gpu,nvidia,amd

- include: nvidia.yml
  when: graphics.stdout.find('NVIDIA') != -1
  tags: gpu,nvidia

- include: amd.yml
  when: graphics.stdout.find('AMD') != -1
  tags: gpu,amd

- include: intel.yml
  when: graphics.stdout.find('Intel') != -1
  tags: gpu,amd

- name: install vulkan support
  pacman:
    name: "{{ vulkan_packages }}"
    update_cache: true
  tags: gpu,amd,intel,nvidia
