---
- set_fact:
    nvidia_packages: "{{ nvidia_packages }} {{ nvidia_packages_lib32 }}"
  when: ansible_architecture == "x86_64"
  tags: nvidia

- name: install nvidia driver
  pacman:
    name: nvidia
    update_cache: true
  tags: nvidia

- name: enable rootless xorg
  template:
    src: Xwrapper.config
    dest: /etc/X11/
  tags: nvidia
