---
- name: find graphics hardware
  shell: lspci | grep -e VGA -e 3D
  register: graphics
  changed_when: false
  become: false
  tags: nvidia

- include: nvidia.yml
  when: graphics.stdout.find('NVIDIA')
  tags: nvidia
