---
- name: find graphics hardware
  shell: lspci | grep -e VGA -e 3D
  register: graphics
  changed_when: false
  become: false
  tags: gpu,amd,intel,nvidia

- set_fact: vlk_pkg="{{ vlk_pkg }} + {{ vlk_pkg_lib32 }}"
  when: ansible_architecture == "x86_64"
  tags: gpu,amd,intel,nvidia

- block:
  - import_tasks: nvidia.yml
    when: graphics.stdout.find('NVIDIA') != -1
    tags: nvidia

  - import_tasks: amd.yml
    when: graphics.stdout.find('AMD') != -1
    tags: amd

  - import_tasks: intel.yml
    when: graphics.stdout.find('Intel') != -1
    tags: intel
  tags: gpu

- name: install gpu drivers
  pacman:
    name: "{{ driver_pkg }}"
    update_cache: true
  when: driver_pkg | length > 0
  tags: gpu,amd,intel,nvidia

- name: install vulkan drivers
  pacman:
    name: "{{ vlk_pkg }}"
    update_cache: true
  tags: gpu,amd,intel,nvidia
