---
- block:
  - name: set nvidia packages
    set_fact: driver_pkg="{{ nvidia_pkg }} + {{ nvidia_pkg_lib32 }}"
    when: ansible_architecture == "x86_64"

  - name: set nvidia packages (x86)
    set_fact: driver_pkg={{ nvidia_pkg }}
    when: ansible_architecture == "x86"

  - name: enable rootless xorg
    template:
      src: Xwrapper.config
      dest: /etc/X11/
    become: true

  tags: nvidia
  become: false
