---
- name: add [local] section
  lineinfile:
    dest: /etc/pacman.conf
    regexp: '^\[local\]'
    line: '[local]'
  tags: packages

- name: include ansible.conf
  lineinfile:
    dest: /etc/pacman.conf
    regexp: '^Include = /etc/pacman.d/ansible.conf'
    line: 'Include = /etc/pacman.d/ansible.conf'
  tags: packages

- name: add multilib support
  template:
    src: ansible.conf
    dest: /etc/pacman.d/ansible.conf
  when: ansible_architecture == "x86_64"
  tags: packages

- name: upgrade all packages
  pacman:
    upgrade: true
    update_cache: true
  tags: packages

- name: install user packages
  pacman:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items: "{{ packages }}"
  tags: packages
