---
- name: include multilib
  lineinfile:
    dest: /etc/pacman.conf
    regexp: '^Include = /etc/pacman.d/multilib'
    line: 'Include = /etc/pacman.d/multilib'
  when: ansible_architecture == "x86_64"
  tags: packages

- name: add multilib support
  template:
    src: multilib
    dest: /etc/pacman.d/multilib
  when: ansible_architecture == "x86_64"
  tags: packages

- name: upgrade all packages
  pacman:
    upgrade: true
    update_cache: true
  tags: packages

- name: install user packages
  pacman:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items: "{{ packages }}"
  tags: packages
