---
- name: install pulseaudio
  pacman:
    name: "{{ pulseaudio.packages.x86_64 }}"
    update_cache: true
  tags: pulseaudio

- name: install 32-bit libs
  pacman:
    name: "{{ pulseaudio.packages.x86 }}"
    update_cache: true
  when: ansible_architecture == "x86_64"
  tags: pulseaudio
