---
- name: setup time zone
  file:
    src: /usr/share/zoneinfo/Europe/Stockholm
    dest: /etc/localtime
    state: link

- name: set hardware clock
  command: hwclock --systohc
  args:
    creates: /etc/adjtime
