---
- name: setup time zone
  file:
    src: /usr/share/zoneinfo/Europe/Stockholm
    dest: /etc/localtime
    state: link
  tags: time-zone

- name: set hardware clock
  command: hwclock --systohc
  args:
    creates: /etc/adjtime
  tags: time-zone
