---
- name: setup time zone
  file:
    src: /usr/share/zoneinfo/Europe/Stockholm
    dest: /etc/localtime
    state: link
  tags: time-zone

- name: generate /etc/adjtime
  command: hwclock --systohc
  args:
    creates: /etc/adjtime
  tags: time-zone

- name: get /etc/adjtime
  command: cat /etc/adjtime
  changed_when: false
  register: adjtime
  tags: time-zone

- name: set hardware clock to utc
  command: hwclock --systohc --utc
  when: adjtime.stdout.find('UTC') == -1
  tags: time-zone
