---
- block:
  - name: set gnome scaling factor
    gsetting:
      key: org.gnome.desktop.interface.scaling-factor
      value: 'uint32 2'
    with_items:
      - "{{ hidpi.users }}"
      - gdm

  # unicode error without root?
  - name: check if app exists
    stat: path={{ item }}
    register: apps
    with_items: "{{ hidpi_stat_files }}"
    become_user: root

  - name: set spotify scale factor
    template:
      src: spotify.desktop
      dest: "{{ hidpi_dirs.0 }}"
    with_items: "{{ hidpi.users }}"
    when: apps.results[0].stat.exists

  - name: install steam hidpi skin
    git:
      repo: "{{ hidpi_steam_url }}"
      dest: "{{ hidpi_dirs.1 }}"
    with_items: "{{ hidpi.users }}"
    when: apps.results[1].stat.exists

  become_user: "{{ item }}"
  tags: hidpi
