---
- block:
  - name: install gnupg deps
    pacman:
      name: "{{ gnupg_packages }}"
      update_cache: true

  - name: setup skel dirs
    file:
      path: "/etc/skel/{{ item.dir }}"
      mode: "{{ item.mode }}"
      state: directory
    with_items: "{{ gnupg_dirs }}"

  - name: setup skel config
    template:
      src: "{{ item.file }}"
      dest: "/etc/skel/{{ item.file }}"
      mode: "{{ item.mode }}"
    with_items: "{{ gnupg_files }}"

  - name: setup user dirs
    file:
      path: "/home/{{ item[0] }}/{{ item[1].dir }}"
      mode: "{{ item[1].mode }}"
      state: directory
    with_nested:
      - "{{ yubikey.users }}"
      - "{{ gnupg_dirs }}"
    become_user: "{{ item[0] }}"

  - name: setup user config
    template:
      src: "{{ item[1].file }}"
      dest: "/home/{{ item[0] }}/{{ item[1].file }}"
      mode: "{{ item[1].mode }}"
    with_nested:
      - "{{ yubikey.users }}"
      - "{{ gnupg_files }}"
    become_user: "{{ item[0] }}"

  - name: setup ssh pkcs11 provider
    lineinfile:
      dest: /etc/ssh/ssh_config
      line: PKCS11Provider /usr/lib/opensc-pkcs11.so

  - block:
    - name: setup pcscd.socket
      systemd:
        name: pcscd.socket
        state: started
        enabled: true
    rescue:
    - name: setup pcscd.socket manually
      file:
        src: "{{ item.src | default(omit) }}"
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      with_items: "{{ gnupg_rescue }}"

  become: true
  tags: gnupg,gpg,gpg-agent,yubikey
