---
- name: install nvidia driver
  pacman:
    name: nvidia
    update_cache: true
  tags: nvidia

- name: install 32-bit nvidia libs
  pacman:
    name: lib32-nvidia-libgl
    update_cache: true
  when: ansible_architecture == "x86_64"
  tags: nvidia

- name: enable rootless xorg
  template:
    src: Xwrapper.config
    dest: /etc/X11/
  tags: nvidia
