---
- name: register graphics
  shell: lspci | grep -e VGA -e 3D
  register: graphics
  changed_when: false
  tags: display-drivers

- name: install nvidia driver
  pacman:
    name: nvidia
    update_cache: true
  when: graphics.stdout.find('NVIDIA') != -1
  tags: display-drivers

- name: install 32-bit nvidia libs
  pacman:
    name: lib32-nvidia-libgl
    update_cache: true
  when:
    - graphics.stdout.find('NVIDIA') != -1
    - ansible_architecture == "x86_64"
  tags: display-drivers
