---
- name: get /tmp mount options
  shell: 'cat /proc/mounts | egrep "\s/tmp\s" | awk "{ print $4 }"'
  changed_when: false
  register: aur_tmp_mnt_opt
  become: false

- name: remount /tmp with exec
  command: mount -o remount,exec /tmp
  args:
    warn: false
  when: aur_tmp_mnt_opt.stdout.find('noexec') != -1
  notify: remount /tmp
  become: true

- name: install dependencies
  pacman:
    name: base-devel
    update_cache: true
  become: true

- name: setup build dir
  file:
    path: "{{ aur_work_dir }}"
    owner: "{{ ansible_user }}"
    mode: 0755
    state: directory
  become: true

- name: install aur packages
  makepkg:
    name: "{{ item.pkg | default('') }}"
    state: present
    as_deps: "{{ item.dep | default(false) }}"
    build_dir: "{{ aur_work_dir }}"
  with_items: "{{ aur.install | default(aur_default_install) }}"
  ignore_errors: true
  become: true

- name: setup yaourtrc
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0644
  with_items: "{{ aur_files }}"
  become: true
