---
- name: enable intel microcode updates
  pacman:
    name: intel-ucode
    update_cache: true
  when: "'GenuineIntel' in ansible_processor"
  tags: systemd-boot

- name: register root device
  shell: 'cat /etc/fstab | egrep "\s/\s" | cut -d" " -f1'
  register: root_device
  changed_when: false
  tags: systemd-boot

- name: check install state
  command: bootctl status
  register: install_state
  changed_when: false
  tags: systemd-boot 

# This is not perfect, because efivars contains data from old installations,
# that might point to the wrong ESP or even a non-existing partition.

- name: remount efivars read-write
  command: mount -t efivarfs -o remount,rw /sys/firmware/efi/efivars
  args:
    warn: false
  when: install_state.stdout.find('Linux Boot Manager') == -1
  register: efivarfs_mount
  tags: systemd-boot

- name: install systemd-boot to esp
  command: "bootctl --path={{ systemd_boot_esp }} install"
  register: install_result
  failed_when: install_result.rc >= 2
  when: efivarfs_mount | changed
  tags: systemd-boot

- name: remount efivars read-only
  command: mount -t efivarfs -o remount,ro /sys/firmware/efi/efivars
  args:
    warn: false
  when: efivarfs_mount | changed
  tags: systemd-boot

- name: setup systemd-boot dirs
  file:
    dest: "{{ item.dir }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ systemd_boot_dirs }}"
  tags: systemd-boot

- name: setup systemd-boot files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ systemd_boot_files }}"
  tags: systemd-boot
