---
- name: setup hostname
  hostname: name={{ arch_hostname }}
  register: hostname_result
  ignore_errors: true
  when: not chroot_mode
  tags: network,hostname

# First task need dbus running, which fails in a chroot
- name: fallback hostname setup
  template:
    src: hostname.j2
    dest: /etc/hostname
  when: hostname_result|failed or chroot_mode
  tags: network,hostname

- name: setup hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags: network,hostname
