---
- block:
  - name: add preset items
    set_fact: menu_files={{ menu_preset }}
    when:
      - (menu.hide_items.preset is undefined) or
        (menu.hide_items.preset)

  - name: add custom items
    set_fact: menu_files="{{ menu_files }} + {{ menu.hide_items.custom }}"
    when:
      - menu.hide_items.custom is defined
      - menu.hide_items.custom | length > 0

  - name: setup applications dir
    file:
      path: /home/{{ item }}/.local/share/applications
      state: directory
    with_items: "{{ menu.hide_items.users }}"
    become_user: "{{ item }}"

  - name: hide menu items
    template:
      src: template.desktop
      dest: "/home/{{ item[1] }}/.local/share/applications/{{ item[0] }}"
      mode: 0644
    with_nested:
      - "{{ menu_files }}"
      - "{{ menu.hide_items.users }}"
    become_user: "{{ item[1] }}"

  when: (menu.hide_items.users is defined) and
        (menu.hide_items.users | length > 0)
  tags: menu
