---
- name: include multilib
  lineinfile:
    dest: /etc/pacman.conf
    regexp: '^Include = /etc/pacman.d/multilib'
    line: 'Include = /etc/pacman.d/multilib'
  when: ansible_architecture == "x86_64"
  tags: pacman

- name: add multilib support
  template:
    src: multilib
    dest: /etc/pacman.d/multilib
  when: ansible_architecture == "x86_64"
  tags: pacman
