---
- name: install reflector
  pacman:
    name: reflector
    update_cache: true
  tags: reflector

- name: setup reflector dirs
  file:
    path: /etc/pacman.d/hooks
    mode: 0755
    state: directory
  tags: reflector

- name: setup reflector files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ reflector_files }}"
  tags: reflector

- block:
  - name: setup reflector.timer
    systemd:
      name: reflector.timer
      state: started
      enabled: true
  rescue:
  - name: enable reflector.timer manually
    file:
      src: "{{ item.src | default(omit) }}"
      path: "{{ item.path }}"
      state: "{{ item.state }}"
    with_items: "{{ reflector_rescue }}"

  - name: run reflector
    command: '/usr/bin/reflector -p https -l 50 -n 5 --sort rate
             {% for o in reflector_countries %}--country {{ o }} {% endfor %}
             --save /etc/pacman.d/mirrorlist'

  tags: reflector
