---
- name: install reflector
  pacman:
    name: reflector
    update_cache: true
  tags: reflector

- name: setup reflector dirs
  file:
    path: /etc/pacman.d/hooks
    mode: 0755
    state: directory
  tags: reflector

- name: setup reflector files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ reflector_files }}"
  tags: reflector

- name: enable reflector.timer
  service:
    name: reflector.timer
    state: "{{ omit if chroot_mode else 'started' }}"
    enabled: true
  tags: reflector

- name: run reflector
  command: '/usr/bin/reflector -p https -l 50 -n 5 --sort rate
           --country Sweden --country Denmark --country Norway
           --save /etc/pacman.d/mirrorlist'
  when: chroot_mode
  tags: reflector
