---
- name: install yubikey dependencies
  pacman:
    name: "{{ yubikey_packages }}"
    update_cache: true
  tags: yubikey

- name: setup skel dirs
  file:
    path: "/etc/skel/{{ item.dir }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items: "{{ yubikey_directories }}"
  tags: yubikey

- name: setup skel config
  copy:
    src: "{{ item.file }}"
    dest: "/etc/skel/{{ item.file }}"
    mode: "{{ item.mode }}"
  with_items: "{{ yubikey_files }}"
  tags: yubikey

- name: setup user dirs
  file:
    path: "/home/{{ item[0] }}/{{ item[1].dir }}"
    mode: "{{ item[1].mode }}"
    state: directory
  with_nested:
    - "{{ yubikey.users }}"
    - "{{ yubikey_directories }}"
  become_user: "{{ item[0] }}"
  tags: yubikey

- name: setup user config
  copy:
    src: "{{ item[1].file }}"
    dest: "/home/{{ item[0] }}/{{ item[1].file }}"
    mode: "{{ item[1].mode }}"
  with_nested:
    - "{{ yubikey.users }}"
    - "{{ yubikey_files }}"
  become_user: "{{ item[0] }}"
  tags: yubikey

- name: setup ssh pkcs11 provider
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: PKCS11Provider /usr/lib/opensc-pkcs11.so
  tags: yubikey

- name: start pcscd.socket
  service:
    name: pcscd.socket
    state: "{{ omit if chroot_mode else 'started' }}"
    enabled: true
  tags: yubikey

- name: enable user gpg-agent.service
  file:
    src: "/home/{{ item[0] }}/{{ item[1].target }}"
    path: "/home/{{ item[0] }}/{{ item[1].link }}"
    state: link
  with_nested:
    - "{{ yubikey.users }}"
    - "{{ yubikey_links }}"
  become_user: "{{ item[0] }}"
  tags: yubikey
