---
- block:
  - name: setup filesystem modules
    set_fact:
      mkinitcpio_modules: "{{ mkinitcpio_modules }} + {{ item.modules }}"
    with_items: "{{ mkinitcpio }}"

  - name: install filesystem deps
    pacman:
      name: "{{ item.utils | default(omit) }}"
      update_cache: true
    with_items: "{{ mkinitcpio }}"

  when: lookup('file', '/etc/fstab').find(item.filesystem) != -1
  tags: mkinitcpio,fstab,dm-crypt

- name: setup disk encryption
  set_fact:
    mkinitcpio_hooks: "{{ mkinitcpio_hooks }} + ['lvm2', 'encrypt']"
    mkinitcpio_files: "{{ mkinitcpio_files }} + ['/crypto_keyfile.bin']"
  when: boot_encryption.enabled
  tags: mkinitcpio,dm-crypt

- name: setup mkinitcpio
  template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
    mode: 0644
  notify: mkinitcpio
  tags: mkinitcpio,fstab,dm-crypt
