---
- block:
  - name: setup systemd-timesyncd.service
    systemd:
      name: systemd-timesyncd
      state: started
      enabled: true
  rescue:
  - name: enable systemd-timesyncd.service manually
    file:
      src: "{{ item.src | default(omit) }}"
      path: "{{ item.path }}"
      state: "{{ item.state }}"
    with_items: "{{ systemd_timesyncd_rescue }}"
  tags: systemd-timesyncd,ntp
