---
- name: install networkmanager
  pacman:
    name: networkmanager
    update_cache: true
  tags: networkmanager

- block:
  - name: setup NetworkManager.service
    systemd:
      name: NetworkManager
      state: started
      enabled: true
  rescue:
  - name: enable NetworkManager.service manually
    file:
      src: "{{ item.src | default(omit) }}"
      path: "{{ item.path }}"
      state: "{{ item.state }}"
    with_items: "{{ networkmanager_rescue }}"
  tags: networkmanager
