---
- name: install networkmanager
  pacman:
    name: networkmanager
    update_cache: true
  tags: networkmanager

- name: start networkmanager
  service:
    name: NetworkManager
    state: "{{ omit if chroot_mode else 'started' }}"
    enabled: true
  tags: networkmanager
